name: deploy to lambda

on: [push]

jobs:
  deploy_jar:
    name: deploy lambda function
    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: build with Maven
        run: mvn clean package

      - name: list target directory
        run: ls -la target

      - name: install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: configure AWS CLI
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set region "${{ secrets.AWS_REGION }}"

      - name: deploy to lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws lambda update-function-code --function-name segundaFuncao --zip-file fileb://target/lambda-java-1.0-SNAPSHOT.jar
